#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "Components/SphereComponent.h"
#include "GameFramework/ProjectileMovementComponent.h"
#include "Kismet/GameplayStatics.h"
#include "Asteroid.h"
#include "Projectile.generated.h"


// This class defines the behavior of projectiles. Projectiles are game objects generated by the player
// that deal damage to asteroids and are destroyed on collision or after a set time.
UCLASS()
class ARDEMO3_API AProjectile : public AActor
{
    // Required UE4 macro for unreal header code
    GENERATED_BODY()
    
public:
    // Sets default values for this actor's properties
    AProjectile();
    
protected:
    // Master function for setting initial state; called when spawned
    virtual void BeginPlay() override;
    
    // Assigns material to spawned actor mesh
    void AssignMaterials(UStaticMeshComponent*);
    
    // Detects collision with other actors
    UFUNCTION()
    void OnProjectileOverlap(UPrimitiveComponent* overlappedComp, AActor* otherActor, UPrimitiveComponent* otherComp, int32 otherBodyIndex, bool bFromSweep, const FHitResult& SweepResult);
    
    // Hit box component
    UPROPERTY()
    USphereComponent* collider;
    
    UPROPERTY()
    UStaticMeshComponent* SphereMesh;
    
    UPROPERTY()
    UMaterialInstance* SphereMaterial;
    
    UPROPERTY()
    UProjectileMovementComponent * projectileMovement;
    
    UPROPERTY()
    UParticleSystem* ExplosionEffect;
    
    UPROPERTY()
    USoundBase* FireSound;
};
