#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "Components/SphereComponent.h"
#include "GameFramework/ProjectileMovementComponent.h"
#include "Kismet/GameplayStatics.h"
#include "Projectile.generated.h"


// This class defines the behavior of projectiles. Projectiles are game objects generated by the player
// that deal damage to asteroids and are destroyed on collision or after a set time.
UCLASS()
class ARDEMO3_API AProjectile : public AActor
{
    // Required UE4 macro for unreal header code
    GENERATED_BODY()
    
public:
    // Sets default values for this actor's properties
    AProjectile();
    
protected:
    // Master function for setting initial state; called when spawned
    virtual void BeginPlay() override;
    
    // Assigns material to spawned actor mesh
    void AssignMaterials(UStaticMeshComponent*);
    
    UFUNCTION()
    void OnProjectileHit(UPrimitiveComponent* HitComp, AActor* OtherActor, UPrimitiveComponent* OtherComp, FVector NormalImpulse, const FHitResult& Hit);
    
    // Hit box component
    UPROPERTY()
    USphereComponent* collider;
    
    UPROPERTY()
    UStaticMeshComponent* SphereMesh;
    
    UPROPERTY()
    UMaterialInstance* SphereMaterial;
    
    UPROPERTY()
    UProjectileMovementComponent * projectileMovement;
    
    UPROPERTY()
    UParticleSystem* ExplosionEffect;
    
    UPROPERTY()
    USoundBase* FireSound;
};
